### ISSUE TITLE
release 包混淆后，请求接口提示 Missing type parameter

### ISSUE THREAD

**Issue by appdev** [liujingxing/rxhttp#396]
项目接口、`Parser`相关配置都使用 Kotlin 开发
gradle 配置文件中，开启混淆后，访问任何接口都会提示 `Missing type parameter`。关闭混淆正常。

日志可以看到。解析器中没有泛型 
开启后，没有泛型的
![image](https://user-images.githubusercontent.com/9107717/183586758-94943e39-3241-4a79-98a1-b7326ea23778.png)
关闭混淆后，带有泛型的
![image](https://user-images.githubusercontent.com/9107717/183586898-34fe7e35-9120-47c4-91e4-0ffd5a31a1bf.png)

**Comment by liujingxing** [comment]
经过一番筛查，发现是打包时，开启混淆优化导致的，开启后，`inline + reified`方法内部，获取泛型类型会失败，这应该属于kotlin的一个bug，暂时有以下两个解决方案：

- 添加`-dontoptimize`到`proguard-rules.pro`文件中
- 使用`proguard-android.txt`替代`proguard-android-optimize.txt`文件

以上两个方案，都会关闭混淆优化，google官方的建议是使用第二种关闭混淆优化。

至于为啥开启优化后，获取泛型类型为啥会失败，我在`proguard-android-optimize.txt`文件中，找到这么一段话

`Adding optimization introduces certain risks, since for example not all optimizations performed by ProGuard works on all versions of Dalvik.  The following flags turn off various optimizations known to have issues, but the list may not be complete or up to date. (The "arithmetic" optimization can be used if you are only targeting Android 2.0 or later.)  Make sure you test thoroughly if you go this route.`

简单翻译下，就是`添加优化会带来一定的风险，如果开启，就一定要详细测试`


在下个版本中，会使用`typeOf`方法获取泛型类型，以规避这个问题

**Comment by liujingxing** [comment]
补充下必现方式

1、定义一个顶级函数，返回泛型具体类型
```kotlin
//TypeToken是Gson库里的类
public inline fun <reified T> type() = object : TypeToken<T>() {}.type
```
2、在伴生对象中调用`type`方法
```
object TypeUtil {

    fun typeOf() {
        val type = type<List<String>>()
    }
}
```
3、在任意地方调用`typeOf`方法

最后打包时，开启混淆优化，打包后，安装测试即可

**Comment by liujingxing** [comment]
[RxHttp v2.9.2版本已解决](https://github.com/liujingxing/rxhttp/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v292)
